---

- name: Adding users
  user:
    name: "{{ user.username }}"
    comment: "{{ user.username|default(user.username) }}"
    home: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username ) }}"
    group: "{{ user.group|default(sftp_users_group) }}"
    groups: "{{ user.groups|default(sftp_users_groups)|join(',') }}"
    password: "{{ user.password }}"
    shell: /usr/sbin/nologin
  tags:
    - networking
    - sftp
    - users

- name: Setting users home permission
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - networking
    - sftp
    - users

- name: Adding users ssh folder
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/.ssh"
    owner: "{{ user.username }}"
    group: "{{ user.group|default(sftp_users_group) }}"
    state: directory
    mode: 0700
  tags:
    - networking
    - sftp
    - users

- name: Adding authorized keys
  template:
    src: home-user-ssh-authorized_keys.j2
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/.ssh/authorized_keys"
    owner: "{{ user.username }}"
    group: "{{ user.group|default(sftp_users_group) }}"
    mode: 0600
  tags:
    - networking
    - sftp
    - users

- name: Adding users chroot folder
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot"
    state: directory
    owner: root
    group: "{{ user.group|default(sftp_users_group) }}"
    mode: 0755
  tags:
    - networking
    - sftp
    - users

- name: Adding users folders
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot/{{ item }}"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.group|default(sftp_users_group) }}"
    mode: 0775
  with_items: "{{ sftp_users_folders }}"
  tags:
    - networking
    - sftp
    - users

- name: Configuring users sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ 'Match USER ' ~ user.username ~ '\n\tAllowTcpForwarding no\n\tForceCommand internal-sftp\n\tPasswordAuthentication yes\n\tChrootDirectory %h/chroot' }}"
    regexp: "^Match USER {{ user.username }}"
    validate: "/usr/sbin/sshd -T -f %s"
    insertbefore: "^{{ sftp_placeholder_end }}"
    state: present
  notify: restart ssh
  tags:
    - networking
    - sftp
    - users

- name: Clearing fstab config
  command: >
    sed -in '/{{ sftp_placeholder_start }}/,/{{ sftp_placeholder_end }}/d' /etc/fstab
  tags:
    - networking
    - sftp
    - config

- name: Adding fstab config placeholder
  lineinfile:
    state: present
    dest: /etc/fstab
    line: "{{ sftp_placeholder_start ~ '\n' ~ sftp_placeholder_end }}"
  tags:
    - networking
    - sftp
    - users

- name: Adding mount point folder
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot/mnt"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - networking
    - sftp
    - users

- name: Unmounting old folders
  command: >
    find {{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot/mnt -maxdepth 1 -mindepth 1 -type d -exec umount {} \;
  tags:
    - networking
    - sftp
    - users

- name: Adding mount point folders
  file:
    dest: "{{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot/mnt/{{ item.name }}"
    owner: "{{ user.username }}"
    group: "{{ user.group|default(sftp_users_group) }}"
    state: directory
    mode: 0775
  with_items: "{{ user.mount_points }}"
  tags:
    - networking
    - sftp
    - users


- name: Adding users fstab
  lineinfile:
    state: present
    dest: /etc/fstab
    line: "{{ item.path }} {{ user.home|default(sftp_users_home ~ '/' ~ user.username) }}/chroot/mnt/{{ item.name }} none defaults,bind 0 0"
    insertbefore: "^{{ sftp_placeholder_end }}"
  notify: mount all
  with_items: "{{ user.mount_points }}"
  tags:
    - networking
    - sftp
    - users
